apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: nginx:1.16  # Old image version
        ports:
        - containerPort: 80
        securityContext:
          privileged: true  # Privileged container (flagged as insecure)
