name: Auto Assign Code Owners

on:
  pull_request:
    types: [opened, synchronize]  # Trigger when a PR is opened or updated

jobs:
  auto_assign_codeowners:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Required to assign users to PRs
      contents: read        # Required to read the CODEOWNERS file

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        run: |
          echo "::set-output name=files::$(git diff --name-only origin/main HEAD)"
      
      - name: Find CODEOWNERS
        id: find_codeowners
        run: |
          CODEOWNERS_FILE=".github/CODEOWNERS"
          if [[ -f "$CODEOWNERS_FILE" ]]; then
            codeowners=""
            for file in ${{ steps.changed_files.outputs.files }}; do
              owners=$(grep -E "^$file" "$CODEOWNERS_FILE" | awk '{print $2}' | sort -u)
              codeowners+="$owners "
            done
            echo "::set-output name=codeowners::$(echo $codeowners | tr ' ' '\n' | sort -u | tr '\n' ' ')"
          else
            echo "No CODEOWNERS file found."
            echo "::set-output name=codeowners::"
          fi

      - name: Auto-assign code owners
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ steps.find_codeowners.outputs.codeowners }}
          numOfAssignee: 1  # Number of assignees to assign
