name: Security Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC

permissions:
  contents: read

jobs:
  # Trivy to do Secret Scanning and SCA
  fs-scan:
    permissions:
      contents: read            # for actions/checkout to fetch code
    name: Secret Scanning & SCA
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Trivy in fs mode, create a JSON report
      - name: Run Trivy in fs mode, generate JSON vulnerability report
        uses: aquasecurity/trivy-action@master  #trivy-action says 0.28.0
        with:
          scan-type: "fs"
          output: 'trivy-fs_json-report.json'
          format: 'json'
          scan-ref: '.'
          exit-code: '0'
          # Enable next line for ad-hoc analysis
          #trivy-config: trivy.yaml  # I should create this file, in case
      
      # Upload the JSON report
      - name: Upload vulnerability scan results (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs_json-report
          path: trivy-fs_json-report.json
          retention-days: 30

      # Run Trivy in fs mode, create a SARIF report
      - name: Run Trivy in fs mode, generate SARIF vulnerability report
        uses: aquasecurity/trivy-action@master  #trivy-action says 0.28.0
        with:
          scan-type: "fs"
          output: 'trivy-fs_sarif-report.sarif'
          format: 'sarif'
          scan-ref: '.'
          hide-progress: true
          exit-code: '0'
          # On a subsequent call to the action we know Trivy is already installed so can skip this
          skip-setup-trivy: true
          # Enable next line for ad-hoc analysis
          #trivy-config: trivy.yaml  # I should create this file, in case

      # Upload SARIF results for IaC scanning to GitHub Security tab
      - name: Upload vulnerability scan results (sarif)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs_sarif-report.sarif'

      # Run Trivy in fs mode, failing in case of High/Critical vulnerabilities
      - name: Run Trivy in fs mode, fail build on high/criticial vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: 'table'
          scan-ref: '.'
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'
          skip-setup-trivy: true

  # Trivy to do Infrastructure as Code (IaC) scanning
  iac-scan:
    permissions:
      contents: read            # for actions/checkout to fetch code
      security-events: write    # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read             # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: IaC Analysis
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase
      - name: Checkout code
        uses: actions/checkout@v4       

      # Run Trivy in config mode, create sarif report
      - name: Run Trivy in IaC mode, fail build on high/criticial vulnerabilities
        uses: aquasecurity/trivy-action@master  #trivy-action says 0.28.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-iac_sarif-report.sarif'
          # For now it is 0, will be promoted to 1
          exit-code: '0' # Fail if HIGH/CRITICAL vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # Upload SARIF results for IaC scanning to GitHub Security tab
      - name: Upload Trivy IaC scan results (sarif)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-iac_sarif-report.sarif'


  # Bandit to do Static Application Security Test (SAST)?


  # Trivy to do Container Scanning?


  # OWASP ZAP to do Dynamic Application Security Test (DAST)?
